# Customer VPN Connections
- customer_name:
  customer_description:
  customer_gateway:
  customer_tunnel: 

- customer_name:
  customer_description:
  customer_gateway:
  customer_tunnel: 

- customer_name:
  customer_description:
  customer_gateway:
  customer_tunnel: 

- customer_name:
  customer_description:
  customer_gateway:
  customer_tunnel: 
